### ISSUE TITLE
Everypay\Everypay\Block\Magento\Customer\Form\Edit does not exist

### ISSUE THREAD

**Issue by Parism** [everypay/everypay-magento2#2]
In your app/code/Everypay/Everypay/etc/di.xml you have this preference : **preference for="Magento\Customer\Block\Form\Edit" type="Everypay\Everypay\Block\Magento\Customer\Form\Edit"**  but there is no Everypay\Everypay\Block\Magento\Customer\Form\Edit.php file in your module.

**Comment by nikosrigas** [comment]
Dear Parism

Thank you for your notice, the issue has been resolved.
